spring:
  application:
    name: weatherforecast

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    # show-sql: true

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: BASIC
          OpenMeteoClient:
            connectTimeout: 10000
            readTimeout: 20000
            loggerLevel: BASIC

resilience4j:
  retry:
    instances:
      weatherForecastSyncRetry:
        max-attempts: 3
        wait-duration: 2s

  circuitbreaker:
    instances:
      weatherForecastSyncCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

  ratelimiter:
    instances:
      weatherForecastSyncRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 1s

  bulkhead:
    instances:
      weatherForecastSyncBulkhead:
        max-concurrent-calls: 5

logging:
  level:
    com.hendersonkleber.weatherforecast.OpenMeteoClient: DEBUG
    com.hendersonkleber.weatherforecast: DEBUG