UPDATE city
SET priority = 'HIGH'
WHERE (name_normalized, state) IN (
                                   ('porto velho', 'RO'),
                                   ('rio branco', 'AC'),
                                   ('manaus', 'AM'),
                                   ('boa vista', 'RR'),
                                   ('belem', 'PA'),
                                   ('macapa', 'AP'),
                                   ('palmas', 'TO'),
                                   ('sao luis', 'MA'),
                                   ('teresina', 'PI'),
                                   ('fortaleza', 'CE'),
                                   ('natal', 'RN'),
                                   ('joao pessoa', 'PB'),
                                   ('recife', 'PE'),
                                   ('maceio', 'AL'),
                                   ('aracaju', 'SE'),
                                   ('salvador', 'BA'),
                                   ('belo horizonte', 'MG'),
                                   ('vitoria', 'ES'),
                                   ('rio de janeiro', 'RJ'),
                                   ('sao paulo', 'SP'),
                                   ('curitiba', 'PR'),
                                   ('florianopolis', 'SC'),
                                   ('porto alegre', 'RS'),
                                   ('campo grande', 'MS'),
                                   ('cuiaba', 'MT'),
                                   ('goiania', 'GO'),
                                   ('brasilia', 'DF')
    );

UPDATE city
SET priority = 'MEDIUM'
WHERE (name_normalized, state) IN (
                                   ('campinas', 'SP'),
                                   ('guarulhos', 'SP'),
                                   ('sao bernardo do campo', 'SP'),
                                   ('santo andre', 'SP'),
                                   ('osasco', 'SP'),
                                   ('ribeirao preto', 'SP'),
                                   ('sorocaba', 'SP'),
                                   ('mogi das cruzes', 'SP'),
                                   ('sao jose dos campos', 'SP'),
                                   ('santos', 'SP'),
                                   ('diadema', 'SP'),
                                   ('jundiai', 'SP'),
                                   ('carapicuiba', 'SP'),
                                   ('piracicaba', 'SP'),
                                   ('bauru', 'SP'),
                                   ('limeira', 'SP'),
                                   ('nova iguacu', 'RJ'),
                                   ('duque de caxias', 'RJ'),
                                   ('niteroi', 'RJ'),
                                   ('sao goncalo', 'RJ'),
                                   ('belford roxo', 'RJ'),
                                   ('uberlandia', 'MG'),
                                   ('contagem', 'MG'),
                                   ('juiz de fora', 'MG'),
                                   ('betim', 'MG'),
                                   ('montes claros', 'MG'),
                                   ('ribeirao das neves', 'MG'),
                                   ('uberaba', 'MG'),
                                   ('governador valadares', 'MG'),
                                   ('ipatinga', 'MG'),
                                   ('canoas', 'RS'),
                                   ('pelotas', 'RS'),
                                   ('caxias do sul', 'RS'),
                                   ('novo hamburgo', 'RS'),
                                   ('sao leopoldo', 'RS'),
                                   ('londrina', 'PR'),
                                   ('maringa', 'PR'),
                                   ('ponta grossa', 'PR'),
                                   ('cascavel', 'PR'),
                                   ('sao jose dos pinhais', 'PR'),
                                   ('joinville', 'SC'),
                                   ('blumenau', 'SC'),
                                   ('chapeco', 'SC'),
                                   ('criciuma', 'SC'),
                                   ('feira de santana', 'BA'),
                                   ('vitoria da conquista', 'BA'),
                                   ('camacari', 'BA'),
                                   ('itabuna', 'BA'),
                                   ('caucaia', 'CE'),
                                   ('juazeiro do norte', 'CE'),
                                   ('maracanau', 'CE'),
                                   ('jaboatao dos guararapes', 'PE'),
                                   ('olinda', 'PE'),
                                   ('caruaru', 'PE'),
                                   ('aparecida de goiania', 'GO'),
                                   ('anapolis', 'GO'),
                                   ('imperatriz', 'MA'),
                                   ('ananindeua', 'PA'),
                                   ('santarem', 'PA'),
                                   ('varzea grande', 'MT'),
                                   ('rondonopolis', 'MT'),
                                   ('dourados', 'MS'),
                                   ('mossoro', 'RN'),
                                   ('parnamirim', 'RN'),
                                   ('arapiraca', 'AL'),
                                   ('parnaiba', 'PI'),
                                   ('campina grande', 'PB'),
                                   ('serra', 'ES'),
                                   ('vila velha', 'ES'),
                                   ('cariacica', 'ES')
    );